import type { Project } from "./portfolio.types";

export const PROJECTS: readonly Project[] = [
  {
    num: "01",
    tag: "Laravel",
    size: "large",
    year: "2026",
    title: "Business CMS - roles, reports and approvals",
    tags: ["Laravel", "MySQL", "REST API"],
    glyph: "L",
    c1: "#1E40AF",
    c2: "#0a0a0c",
  },
  {
    num: "02",
    tag: "WordPress",
    size: "med",
    year: "2025",
    title: "Service website - Elementor rebuild and SEO cleanup",
    tags: ["WordPress", "Elementor", "Astra"],
    glyph: "W",
    c1: "#DC2626",
    c2: "#1E40AF",
  },
  {
    num: "03",
    tag: "Frontend",
    size: "small",
    year: "2025",
    title: "Portfolio refresh - fast static Next.js site",
    tags: ["Next.js", "TypeScript"],
    glyph: "N",
    c1: "#DC2626",
    c2: "#0a0a0c",
  },
  {
    num: "04",
    tag: "CodeIgniter",
    size: "med",
    year: "2024",
    title: "Legacy app rescue - HMVC modules and bug fixes",
    tags: ["CodeIgniter", "PHP", "Ajax"],
    glyph: "CI",
    c1: "#1E40AF",
    c2: "#DC2626",
  },
  {
    num: "05",
    tag: "Payments",
    size: "small",
    year: "2024",
    title: "Checkout flow - PayPal and gateway integration",
    tags: ["Laravel", "PayPal", "Security"],
    glyph: "$",
    c1: "#0a0a0c",
    c2: "#1E40AF",
  },
  {
    num: "06",
    tag: "E-commerce",
    size: "large",
    year: "2024",
    title: "Online store - responsive catalog and order flow",
    tags: ["WooCommerce", "PHP", "MySQL"],
    glyph: "EC",
    c1: "#DC2626",
    c2: "#1E40AF",
  },
] as const;
