import type { Project } from "./portfolio.types";

export const PROJECTS: readonly Project[] = [
  {
    num: "01",
    tag: "AI · SaaS",
    size: "large",
    year: "2026",
    title: "Atlas — Multi-agent operations dashboard",
    tags: ["Next.js", "OpenAI", "Postgres"],
    glyph: "A",
    c1: "#1E40AF",
    c2: "#0a0a0c",
  },
  {
    num: "02",
    tag: "E-commerce",
    size: "med",
    year: "2025",
    title: "Verdant Goods — Shopify storefront",
    tags: ["Shopify", "Liquid", "GSAP"],
    glyph: "V",
    c1: "#DC2626",
    c2: "#1E40AF",
  },
  {
    num: "03",
    tag: "Brand site",
    size: "small",
    year: "2025",
    title: "Northwind Studio — Editorial portfolio",
    tags: ["Webflow", "Lenis"],
    glyph: "N",
    c1: "#DC2626",
    c2: "#0a0a0c",
  },
  {
    num: "04",
    tag: "AI · Tooling",
    size: "med",
    year: "2025",
    title: "PromptForge — Visual agent builder",
    tags: ["React", "LangChain", "tRPC"],
    glyph: "P",
    c1: "#1E40AF",
    c2: "#DC2626",
  },
  {
    num: "05",
    tag: "WordPress",
    size: "small",
    year: "2024",
    title: "Halcyon Clinic — Booking platform",
    tags: ["WP", "ACF", "Stripe"],
    glyph: "H",
    c1: "#0a0a0c",
    c2: "#1E40AF",
  },
  {
    num: "06",
    tag: "AI · Internal",
    size: "large",
    year: "2024",
    title: "Helios — RAG knowledge base for ops teams",
    tags: ["Pinecone", "Claude", "Notion API"],
    glyph: "He",
    c1: "#DC2626",
    c2: "#1E40AF",
  },
] as const;
