import type { Testimonial } from "./portfolio.types";

const FIVERR_PROFILE = "https://www.fiverr.com/curiousteam";

export const TESTIMONIALS: readonly Testimonial[] = [
  {
    stars: 5,
    quote: "Very good communication skill, know his matter and go extra mile.",
    name: "Jules9292",
    role: "Full Stack Web Applications",
    country: "France",
    date: "3 years ago",
    avatar: "J",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote: "Very nice to work with and is very open minded to make project as needed",
    name: "achillescomfort",
    role: "Help/Consultation",
    country: "United States",
    date: "4 years ago",
    avatar: "A",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "He fixed all the requested issues very well on my Yii1 framework. If something was unclear, he asked me. This simplified the cooperation.",
    name: "fivarthur",
    role: "Full Stack Web Applications",
    country: "Switzerland",
    date: "4 years ago",
    avatar: "F",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote: "Excellent seller",
    name: "vivek033",
    role: "Full Stack Web Applications",
    country: "India",
    date: "4 years ago",
    avatar: "V",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote: "the best and most professional seller i have seen on this platform.",
    name: "vivek033",
    role: "Full Stack Web Applications",
    country: "India",
    date: "4 years ago",
    avatar: "V",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "He is the best designer who know how to handle complex projects so easily. i have done multiple projects with him and will do so. go for him.",
    name: "vivek033",
    role: "Full Stack Web Applications",
    country: "India",
    date: "4 years ago",
    avatar: "V",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote: "Curiousteam now what they doing!",
    name: "chris_df",
    role: "Web development",
    country: "Germany",
    date: "4 years ago",
    avatar: "C",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "This is the second project working with Curiousteam. Very easy to liaise instructions and project was completed very efficiently. He has a lot of experience with website development & php work. Thank you",
    name: "bjubrisl",
    role: "Website development",
    country: "Australia",
    date: "5 years ago",
    avatar: "B",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote:
      "rubel is the best when it comes to work, professionalism, guidance and support. I am going to work with him on many more projects",
    name: "vivek033",
    role: "Custom Websites",
    country: "India",
    date: "5 years ago",
    avatar: "V",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "Very easy to communicate with when discussing website changes. A very professional seller and very capable at his work. He was able to make changes to our landing page and ensure all the links and contact page were working. Will use for other projects in the future. Thanks",
    name: "bjubrisl",
    role: "Website changes",
    country: "Australia",
    date: "5 years ago",
    avatar: "B",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote:
      "This guy is damn good at what he do. Whether he know things or not, he learn them quickly and deliver amazing outputs. He is a fast learner and a reliable person. We'll hire him in our future projects as well.",
    name: "smartattitude51",
    role: "Web application work",
    country: "Sri Lanka",
    date: "5 years ago",
    avatar: "S",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote:
      "outstanding experience, very smart developer not last time, will be more projects in future",
    name: "klingsman",
    role: "Full Stack Web Applications",
    country: "Algeria",
    date: "5 years ago",
    avatar: "K",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "Working with him is always a pleasure. Only if we could find people like him for our company, he is the best. He is my go-to guy for all tech needs. I would hire him without a doubt, he is fast and understanding, he goes above and beyond your expectations. Thank you",
    name: "akshayjain77",
    role: "Tech support",
    country: "India",
    date: "5 years ago",
    avatar: "A",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote:
      "Would definitely recommend, very helpful and thorough in his delivery and kept me informed throughout.",
    name: "laranlcks",
    role: "Web delivery",
    country: "United Kingdom",
    date: "5 years ago",
    avatar: "L",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "He is great with details, communication was easy and his understanding of the WordPress and PHP is second to none. He is responsive and he delivers in time. I would recommend him to everyone. He is my go to guy whenever I need any PHP or wordpress work. Thank you",
    name: "akshayjain77",
    role: "WordPress and PHP",
    country: "India",
    date: "5 years ago",
    avatar: "A",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
    featured: true,
  },
  {
    stars: 5,
    quote: "Excellent job, can't wait to work with them again!",
    name: "chrisregnery",
    role: "Full Stack Web Applications",
    country: "Colombia",
    date: "5 years ago",
    avatar: "C",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "By far the best developer I have work with. This is the first time I actually recommending a Fiverr gig. Awesome dude, Best service.",
    name: "ennis_",
    role: "Full Stack Web Applications",
    country: "Taiwan",
    date: "7 years ago",
    avatar: "E",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote: "best freelancer, perfect work",
    name: "gmaffel",
    role: "Full Stack Web Applications",
    country: "Italy",
    date: "7 years ago",
    avatar: "G",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote:
      "Again, great to work with. Very professional, on time and high quality. We could not be more pleased!",
    name: "brentaford",
    role: "Full Stack Web Applications",
    country: "United States",
    date: "8 years ago",
    avatar: "B",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
  {
    stars: 5,
    quote: "Honest and reliable",
    name: "Jmaze21",
    role: "Full Stack Web Applications",
    country: "Singapore",
    date: "8 years ago",
    avatar: "J",
    platform: "Fiverr",
    sourceUrl: FIVERR_PROFILE,
  },
] as const;
